"""Is this document what it claims to be?

People are sent forged notices, doctored agreements and AI-drafted documents passed off as
official ones. This service looks for **evidence** of that and reports it with the page and the
exact words, so a person can check every finding themselves.

What it deliberately does not do
--------------------------------
It does not guess whether prose "reads like AI" from its style. Stylometric detectors
(perplexity, burstiness, and the commercial services built on them) are unreliable, and they are
worst exactly here: legal and government writing is formal, templated and repetitive, which is
what those detectors score as machine-written. Refusing a citizen's genuine government notice
because a detector disliked its prose is a far worse failure than missing a fake, so that
approach is not used and no score of that kind is produced.

What it does instead is look for things that are *checkable*:

- **Provenance** — what the PDF itself records about the tool that made it and when it was last
  changed. A PDF whose producer is an AI writing tool, or that was modified after it was signed,
  is a fact, not a guess.
- **Leftovers** — text a real issued document would never contain: an assistant's own words
  ("as an AI language model", "here is a draft"), or template placeholders that were never
  filled in ("[Your Name]", "XXXX").
- **Missing official markers** — an official communication with no reference number, no issuing
  authority and no date is not necessarily forged, but it is not something to act on either.

Severity and what follows
-------------------------
- ``high``   — strong, specific evidence. With ``AUTHENTICITY_POLICY=reject`` the document is
               refused; the default policy is to accept it and warn prominently.
- ``medium`` — worth a person's attention; never grounds for refusing on its own.
- ``info``   — context (for example, that the file is a scan).

A verdict is never "fake" or "genuine": it is ``concerns``, ``check`` or ``ordinary``. ClauseLens
reports what it found; whether a document is authentic is for the issuing authority or a lawyer
to say.
"""

import logging
import re
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal

import pymupdf

from app.services.text_utils import normalize_whitespace, snippet_around

logger = logging.getLogger("clauselens.authenticity")

Severity = Literal["high", "medium", "info"]
Verdict = Literal["concerns", "check", "ordinary"]

# Tools that write documents rather than print or scan them. Finding one of these in the PDF's
# own Producer/Creator fields is direct evidence of how the file was made.
AI_WRITING_TOOLS = [
    "chatgpt", "openai", "gpt-4", "gpt-3", "claude", "anthropic", "gemini", "bard",
    "copilot", "jasper", "copy.ai", "writesonic", "gamma.app", "tome.app", "notion ai",
    "quillbot", "grammarly", "deepai", "perplexity",
]  # fmt: skip

# An assistant's own voice, or a template's, left in the text. A real issued document has none
# of these. They are matched literally, so a hit is something the reader can see for themselves.
ASSISTANT_PHRASES = [
    "as an ai language model", "as an ai assistant", "i'm an ai", "i am an ai",
    "i cannot provide legal advice", "i can't provide legal advice",
    "consult a qualified attorney before using this",
    "here is a draft", "here's a draft", "here is a sample", "here's a sample",
    "this is a template", "this template is", "sample document only",
    "feel free to modify", "feel free to customise", "feel free to customize",
    "let me know if you need", "i hope this helps",
    "disclaimer: this document was generated",
    "generated by ai", "ai-generated document",
]  # fmt: skip

# Placeholders a finished document should not contain.
PLACEHOLDER_PATTERNS = [
    r"\[(?:your|insert|enter|name|address|date|party|company|amount|full)\b[^\]]{0,40}\]",
    r"<(?:your|insert|enter|name|address|date|party|company|amount)\b[^>]{0,40}>",
    r"\blorem ipsum\b",
    r"\b(?:xxxx+|yyyy+|zzzz+)\b",
    r"\bABC (?:Company|Corporation|Pvt|Private)\b",
    r"\bJohn Doe\b|\bJane Doe\b",
]
# Deliberately not matched: "Party A" / "Party B". Statutes are full of ordinary sentences like
# "giving such party a reasonable time", and a contract may genuinely label its parties that way.

# Markers a genuine official communication normally carries.
OFFICIAL_MARKERS = {
    # The trailing \b matters: without it "NO" + "TICE" makes the word NOTICE look like a
    # reference number, and a notice with no number at all appears to have one.
    "reference number": r"\b(?:ref(?:erence)?|no|number|f\.?\s?no|diary|file)\b\.?\s*[:\-]?\s*"
    r"[a-z0-9][a-z0-9/\-]{3,}",
    "issuing authority": r"\b(?:government of|ministry of|department of|office of the|"
    r"municipal corporation|authority|commissioner|collector|tahsildar|registrar|secretary)\b",
    "a date": r"\b(?:\d{1,2}[/\-.]\d{1,2}[/\-.]\d{2,4}"
    r"|\d{1,2}\s+(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+\d{4})\b",
    "signature or seal": r"\b(?:signature|signed|sd/-|seal|stamp of|for and on behalf|"
    r"authorised signatory|yours faithfully|yours sincerely)\b",
}
# Only these categories are expected to carry official markers. Acts ("policy") are left out
# on purpose: published law carries no diary number and no signature, and its structure is
# already checked against the published form in services/formats.py.
OFFICIAL_CATEGORIES = frozenset({"government", "public_notice", "court"})

# A modification recorded more than this long after creation is worth mentioning; a PDF saved
# again minutes later is ordinary.
EDIT_GAP_DAYS = 1
MAX_EVIDENCE = 6
# The odd-typeface signal needs a document big enough for "unusual" to mean anything, and
# enough readable words to be a spliced sentence rather than a glyph.
MIN_DOCUMENT_CHARACTERS = 400
ODD_FONT_MAX_SHARE = 0.01
ODD_FONT_MIN_WORDS = 4


class DocumentRejected(Exception):
    """Raised when AUTHENTICITY_POLICY=reject and there is strong evidence against a document.

    Carries the report so the refusal can still show what was found and on which page.
    """

    def __init__(self, reason: str, report: dict[str, Any]) -> None:
        super().__init__(reason)
        self.report = report


@dataclass(frozen=True)
class Signal:
    id: str
    label: str
    severity: Severity
    detail: str
    #: What was found, so the reader can check it. None for signals about absence.
    evidence: str | None = None
    page_number: int | None = None


@dataclass
class Report:
    signals: list[Signal] = field(default_factory=list)
    #: What the PDF records about itself, shown as-is.
    provenance: dict[str, str] = field(default_factory=dict)

    @property
    def verdict(self) -> Verdict:
        if any(s.severity == "high" for s in self.signals):
            return "concerns"
        if any(s.severity == "medium" for s in self.signals):
            return "check"
        return "ordinary"

    @property
    def high(self) -> list[Signal]:
        return [s for s in self.signals if s.severity == "high"]

    def as_dict(self) -> dict[str, Any]:
        return {
            "verdict": self.verdict,
            "provenance": self.provenance,
            "signals": [
                {
                    "id": s.id,
                    "label": s.label,
                    "severity": s.severity,
                    "detail": s.detail,
                    "evidence": s.evidence,
                    "page_number": s.page_number,
                }
                for s in self.signals
            ],
        }


def _parse_pdf_date(value: str) -> datetime | None:
    """PDF dates look like D:20260415103000+05'30'."""
    match = re.match(r"D?:?(\d{4})(\d{2})(\d{2})(\d{2})?(\d{2})?(\d{2})?", value or "")
    if not match:
        return None
    parts = [int(p) if p else 0 for p in match.groups()]
    try:
        return datetime(parts[0], parts[1] or 1, parts[2] or 1, parts[3], parts[4], parts[5])
    except ValueError:
        return None


def _provenance_signals(document: Any, report: Report) -> None:
    metadata = document.metadata or {}
    producer = (metadata.get("producer") or "").strip()
    creator = (metadata.get("creator") or "").strip()
    report.provenance = {
        key: value
        for key, value in (
            ("Made with", producer or creator or "not recorded"),
            ("Created", metadata.get("creationDate", "") or "not recorded"),
            ("Last changed", metadata.get("modDate", "") or "not recorded"),
            ("Title", metadata.get("title", "") or ""),
            ("Author", metadata.get("author", "") or ""),
        )
        if value
    }

    haystack = f"{producer} {creator}".casefold()
    for tool in AI_WRITING_TOOLS:
        if tool in haystack:
            report.signals.append(
                Signal(
                    id="ai_tool_metadata",
                    label="The file says it was made by an AI writing tool",
                    severity="high",
                    detail=(
                        "The PDF's own record of the program that produced it names an AI "
                        "writing tool. An official document is produced by the issuing office, "
                        "not by a chat assistant."
                    ),
                    evidence=producer or creator,
                )
            )
            break

    created = _parse_pdf_date(metadata.get("creationDate", ""))
    modified = _parse_pdf_date(metadata.get("modDate", ""))
    if created and modified:
        if modified < created:
            report.signals.append(
                Signal(
                    id="impossible_dates",
                    label="The file was changed before it was created",
                    severity="high",
                    detail=(
                        "The PDF records a last-changed time earlier than its creation time, "
                        "which cannot happen normally and suggests the dates were altered."
                    ),
                    evidence=f"created {created:%d %b %Y %H:%M}, changed {modified:%d %b %Y %H:%M}",
                )
            )
        elif (modified - created).days >= EDIT_GAP_DAYS:
            report.signals.append(
                Signal(
                    id="edited_later",
                    label="The file was edited after it was first created",
                    severity="medium",
                    detail=(
                        "Ordinary for a draft, but on a signed or issued document it means the "
                        "file was changed after it was made. Ask for the copy the office issued."
                    ),
                    evidence=f"created {created:%d %b %Y}, changed {modified:%d %b %Y}",
                )
            )

    # xref_xref_sections > 1 means the file was saved again on top of an earlier version.
    try:
        updates = document.xref_xref_sections() if hasattr(document, "xref_xref_sections") else 1
    except Exception:  # pragma: no cover - PyMuPDF version differences
        updates = 1
    if isinstance(updates, int) and updates > 1:
        report.signals.append(
            Signal(
                id="incremental_update",
                label="The file contains an earlier version inside it",
                severity="medium",
                detail=(
                    "The PDF was saved again on top of an earlier copy, so something was changed "
                    "after the original was written. On a signed document that is worth asking "
                    "about."
                ),
                evidence=f"{updates} saved revisions",
            )
        )


def _text_signals(pages: list[tuple[int, str]], report: Report) -> None:
    placeholders = [re.compile(pattern, re.I) for pattern in PLACEHOLDER_PATTERNS]
    found_assistant: list[tuple[int, str]] = []
    found_placeholder: list[tuple[int, str]] = []

    for page_number, text in pages:
        lowered = text.casefold()
        for phrase in ASSISTANT_PHRASES:
            index = lowered.find(phrase)
            if index != -1:
                end = index + len(phrase)
                found_assistant.append((page_number, snippet_around(text, index, end)))
        for pattern in placeholders:
            match = pattern.search(text)
            if match:
                found_placeholder.append(
                    (page_number, snippet_around(text, match.start(), match.end()))
                )

    if found_assistant:
        page_number, evidence = found_assistant[0]
        report.signals.append(
            Signal(
                id="assistant_text",
                label="The document contains an AI assistant's own words",
                severity="high",
                detail=(
                    "Wording like this is written by a chat assistant to the person who asked "
                    "it, not by the office issuing a document. It was left in the text."
                ),
                evidence=evidence,
                page_number=page_number,
            )
        )
    if found_placeholder:
        page_number, evidence = found_placeholder[0]
        report.signals.append(
            Signal(
                id="placeholder_text",
                label="Template placeholders were never filled in",
                severity="medium",
                detail=(
                    "A finished document names real people, dates and amounts. Placeholders "
                    "left in it mean this is a template, not an executed document."
                ),
                evidence=evidence,
                page_number=page_number,
            )
        )


def _marker_signals(pages: list[tuple[int, str]], category: str | None, report: Report) -> None:
    if category not in OFFICIAL_CATEGORIES:
        return
    whole = " ".join(text for _, text in pages)
    missing = [
        name for name, pattern in OFFICIAL_MARKERS.items() if not re.search(pattern, whole, re.I)
    ]
    if missing:
        report.signals.append(
            Signal(
                id="missing_official_markers",
                label="Missing the markings an official document usually carries",
                severity="medium" if len(missing) > 1 else "info",
                detail=(
                    "Not found anywhere in this document: "
                    + ", ".join(missing)
                    + ". A genuine official communication almost always carries these, so check "
                    "it against the issuing office before acting on it."
                ),
            )
        )


def _font_signals(document: Any, report: Report) -> None:
    """Text added to a finished PDF usually arrives in a font the rest of the file never uses.

    Held to a high bar on purpose. Emblems, logos, stamps and rotated watermarks all use their
    own font, and flagging those would mark most genuine government documents as suspect. The
    signal only fires for a font carrying several *readable words* on a single page.
    """
    per_page: list[Counter[str]] = []
    words_by_font: dict[str, list[str]] = {}
    for page in document:
        fonts: Counter[str] = Counter()
        try:
            data = page.get_text("dict")
        except Exception:  # pragma: no cover - damaged page
            continue
        for block in data.get("blocks", []):
            for line in block.get("lines", []):
                # Rotated text is a watermark or a stamp, not edited body text.
                dx, dy = line.get("dir", (1.0, 0.0))
                if abs(dy) > 0.05 or dx < 0:
                    continue
                for span in line.get("spans", []):
                    text = span.get("text", "").strip()
                    if text:
                        font = span.get("font", "?")
                        fonts[font] += len(text)
                        words_by_font.setdefault(font, []).extend(text.split())
        per_page.append(fonts)

    overall: Counter[str] = Counter()
    for fonts in per_page:
        overall.update(fonts)
    if not overall or len(overall) < 2 or sum(overall.values()) < MIN_DOCUMENT_CHARACTERS:
        return
    total = sum(overall.values())
    for font, count in overall.items():
        if sum(1 for fonts in per_page if fonts.get(font)) != 1:
            continue
        if count / total >= ODD_FONT_MAX_SHARE:
            continue
        readable = [w for w in words_by_font.get(font, []) if len(w) >= 3 and w.isalpha()]
        if len(readable) < ODD_FONT_MIN_WORDS:
            continue  # a stray glyph, a page number, an emblem — not a spliced sentence
        page_number = next(i for i, fonts in enumerate(per_page, start=1) if fonts.get(font))
        report.signals.append(
            Signal(
                id="odd_font",
                label="A few words use a typeface the rest of the document never uses",
                severity="medium",
                detail=(
                    "That can simply be a logo or a stamp. It is also what altered text looks "
                    "like, so it is worth comparing this page with the original."
                ),
                evidence=f"“{' '.join(readable[:8])}” — {font}, page {page_number} only",
                page_number=page_number,
            )
        )
        break


def _scan_signal(pages: list[tuple[int, str]], report: Report) -> None:
    if not pages or all(len(text.strip()) < 20 for _, text in pages):
        report.signals.append(
            Signal(
                id="image_only",
                label="The pages are images, so the wording was read by text recognition",
                severity="info",
                detail=(
                    "Nothing about the file's own text can be checked, because it has none. A "
                    "scan is normal for a posted document, and also the easiest thing to alter."
                ),
            )
        )


def inspect(pdf_bytes: bytes, pages: list[tuple[int, str]], category: str | None) -> Report:
    """Look for evidence about how this document was made. Never raises."""
    report = Report()
    pages = [(number, normalize_whitespace(text or "")) for number, text in pages]
    try:
        opened = pymupdf.open(stream=pdf_bytes, filetype="pdf")
        with opened as document:
            _provenance_signals(document, report)
            _font_signals(document, report)
    except Exception:
        logger.exception("Could not read the PDF's own record of itself")
    _text_signals(pages, report)
    _marker_signals(pages, category, report)
    _scan_signal(pages, report)
    report.signals = report.signals[:MAX_EVIDENCE]
    return report


def rejection_reason(report: Report) -> str | None:
    """The message to refuse a document with, or None when there is nothing strong enough.

    Only ``high`` signals — direct, checkable evidence — can refuse a document. Nothing here
    refuses one for how its prose reads.
    """
    strong = report.high
    if not strong:
        return None
    first = strong[0]
    # The label is used as written: lowercasing it would turn "AI" into "ai".
    return (
        f"This document was not accepted. {first.label}. {first.detail} "
        "If you believe this is wrong, ask the issuing office for the original file."
    )
