"""document classification

Revision ID: 0a04dcdead83
Revises: 9cdc62d16c2b
Create Date: 2026-09-25 13:47:25.330612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a04dcdead83'
down_revision: Union[str, Sequence[str], None] = '9cdc62d16c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type_id', sa.String(length=80), nullable=True))
    op.add_column('documents', sa.Column('category', sa.String(length=40), nullable=True))
    op.add_column('documents', sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_document_type_id'), 'documents', ['document_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_document_type_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_column('documents', 'classification')
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'document_type_id')
    # ### end Alembic commands ###
