"""fact confidence and normalized value

Revision ID: 6987dfa96850
Revises: 0a04dcdead83
Create Date: 2026-09-25 14:06:21.689409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6987dfa96850'
down_revision: Union[str, Sequence[str], None] = '0a04dcdead83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_facts', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('legal_facts', sa.Column('normalized_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_facts', 'normalized_value')
    op.drop_column('legal_facts', 'confidence')
    # ### end Alembic commands ###
