"""firebase users

Revision ID: 7a634c6b6865
Revises: e351913796d2
Create Date: 2026-09-25 17:59:15.098938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7a634c6b6865'
down_revision: Union[str, Sequence[str], None] = 'e351913796d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###

    # Documents uploaded before sign-in existed get an owner: the local development user.
    # Move them to a Google account later with `uv run python -m scripts.assign_documents`.
    op.execute(
        sa.text(
            "INSERT INTO users (id, created_at, firebase_uid, email, display_name) "
            "SELECT gen_random_uuid(), now(), 'local-dev', 'local-dev@localhost', 'Local user' "
            "WHERE NOT EXISTS (SELECT 1 FROM users WHERE firebase_uid = 'local-dev')"
        )
    )
    op.execute(
        sa.text(
            "UPDATE documents SET user_id = (SELECT id FROM users WHERE firebase_uid = 'local-dev') "
            "WHERE user_id IS NULL"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###
