"""processing_queue

Revision ID: 81ac85c8cd68
Revises: 79238e53fa1e
Create Date: 2026-09-26 02:19:33.673545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '81ac85c8cd68'
down_revision: Union[str, Sequence[str], None] = '79238e53fa1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('processing_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_attempts')
    op.drop_column('documents', 'processing_heartbeat_at')
    # ### end Alembic commands ###
