"""document format

Revision ID: 9cdc62d16c2b
Revises: e38c1d1a3e73
Create Date: 2026-09-25 12:23:06.888642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9cdc62d16c2b'
down_revision: Union[str, Sequence[str], None] = 'e38c1d1a3e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('format', sa.String(length=10), server_default='pdf', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'format')
    # ### end Alembic commands ###
