"""corrected copies

Revision ID: e38c1d1a3e73
Revises: 84d6703f3b96
Create Date: 2026-09-25 05:54:00.966382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e38c1d1a3e73'
down_revision: Union[str, Sequence[str], None] = '84d6703f3b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_document_id', sa.Uuid(), nullable=True))
    op.add_column('documents', sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.create_foreign_key('documents_source_document_id_fkey', 'documents', 'documents', ['source_document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_source_document_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'changes')
    op.drop_column('documents', 'source_document_id')
    # ### end Alembic commands ###
